-- Vidalita audit logs setup
-- IMPORTANT: Run this script in Supabase SQL Editor to fix "invalid input syntax for type uuid" error.
DROP TABLE IF EXISTS audit_logs; 
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT, 
    performer_name TEXT,
    action TEXT NOT NULL,
    target_id TEXT,
    details JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- Since we use custom users table instead of Supabase Auth, 
-- we allow public/anon access for the demo/prototyping phase.
DROP POLICY IF EXISTS "Enable all for everyone" ON audit_logs;
CREATE POLICY "Enable all for everyone" ON audit_logs FOR ALL TO public USING (true);
