-- Vidalita Qarzlar va Taksit tizimi
-- Ushbu skriptni Supabase SQL xotirasiga kochiring va run qiling

-- 1. Qarzlar jadvalini yaratish
CREATE TABLE IF NOT EXISTS debts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
    source_type TEXT CHECK (source_type IN ('POS', 'BEAUTY')),
    source_id BIGINT, -- Sale id yoki Beauty id
    total_amount DECIMAL(15, 2) NOT NULL DEFAULT 0,
    remaining_amount DECIMAL(15, 2) NOT NULL DEFAULT 0,
    due_date DATE,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'overdue')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    notes TEXT
);

-- 2. Qarz to'lovlari xronologiyasi
CREATE TABLE IF NOT EXISTS debt_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debt_id BIGINT REFERENCES debts(id) ON DELETE CASCADE,
    amount DECIMAL(15, 2) NOT NULL,
    payment_method TEXT CHECK (payment_method IN ('CASH', 'CARD', 'TRANSFER')),
    payment_date TIMESTAMPTZ DEFAULT NOW(),
    cash_session_id BIGINT REFERENCES cash_sessions(id) ON DELETE SET NULL, -- Kassaga bog'lash
    processed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    notes TEXT
);

-- 3. RLS siyosatlari bilan xavfsizlik
ALTER TABLE debts ENABLE ROW LEVEL SECURITY;
ALTER TABLE debt_payments ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'debts' AND policyname = 'Enable all for authenticated users'
    ) THEN
        CREATE POLICY "Enable all for authenticated users" ON debts FOR ALL TO authenticated USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'debt_payments' AND policyname = 'Enable all for authenticated users'
    ) THEN
        CREATE POLICY "Enable all for authenticated users" ON debt_payments FOR ALL TO authenticated USING (true);
    END IF;
END
$$;

-- 4. status ni avtomatik yangilaydigan triggerni qo'shamiz
CREATE OR REPLACE FUNCTION update_debt_status()
RETURNS TRIGGER AS $$
BEGIN
    -- Agar yangi remaining_amount 0 yoki undan kichik bo'lsa, qarz to'langan hisoblanadi
    IF NEW.remaining_amount <= 0 THEN
        NEW.status = 'paid';
    ELSIF NEW.due_date IS NOT NULL AND NEW.due_date < CURRENT_DATE THEN
        NEW.status = 'overdue';
    ELSE
        NEW.status = 'pending';
    END IF;

    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_debt_status ON debts;
CREATE TRIGGER trg_update_debt_status
BEFORE UPDATE OF remaining_amount ON debts
FOR EACH ROW
EXECUTE FUNCTION update_debt_status();
