-- FINAL CONSOLIDATED DB SETUP FOR KASSA AND APPOINTMENTS
-- Copy and run this in Supabase SQL Editor

-- 1. Cash Sessions Table
CREATE TABLE IF NOT EXISTS cash_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opened_at TIMESTAMPTZ DEFAULT NOW(),
    closed_at TIMESTAMPTZ,
    opened_by UUID REFERENCES auth.users(id),
    closed_by UUID REFERENCES auth.users(id),
    opening_balance DECIMAL(15, 2) DEFAULT 0,
    closing_balance DECIMAL(15, 2),
    status TEXT DEFAULT 'open' CHECK (status IN ('open', 'closed')),
    notes TEXT
);

-- 2. Link Sales and Beauty Services to Cash Sessions
ALTER TABLE sales ADD COLUMN IF NOT EXISTS cash_session_id BIGINT REFERENCES cash_sessions(id);
ALTER TABLE beauty_services ADD COLUMN IF NOT EXISTS cash_session_id BIGINT REFERENCES cash_sessions(id);

-- 3. Link Appointments to Service Packages
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS service_package_id BIGINT REFERENCES service_packages(id);

-- 4. Update Service Packages Table
ALTER TABLE service_packages ADD COLUMN IF NOT EXISTS session_interval INTEGER; -- interval in days
ALTER TABLE service_packages ADD COLUMN IF NOT EXISTS price_per_session DECIMAL(15, 2);

-- 5. Package Usage Log Table
CREATE TABLE IF NOT EXISTS package_usage_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id BIGINT REFERENCES service_packages(id) ON DELETE CASCADE,
    appointment_id BIGINT REFERENCES appointments(id) ON DELETE SET NULL,
    used_at TIMESTAMPTZ DEFAULT NOW(),
    notes TEXT
);

-- 6. Enable RLS and Create Policies
ALTER TABLE cash_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE package_usage_log ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'cash_sessions' AND policyname = 'Enable all for authenticated users'
    ) THEN
        CREATE POLICY "Enable all for authenticated users" ON cash_sessions FOR ALL TO authenticated USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'package_usage_log' AND policyname = 'Enable all for authenticated users'
    ) THEN
        CREATE POLICY "Enable all for authenticated users" ON package_usage_log FOR ALL TO authenticated USING (true);
    END IF;
END
$$;
