-- KASSA & APPOINTMENTS COLUMN FIX
-- Run this if you get "column does not exist" errors
-- Copy and run this in Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Ensure Service Packages tables exist
CREATE TABLE IF NOT EXISTS service_packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
    service_type TEXT,
    service_name TEXT,
    total_sessions INTEGER,
    remaining_sessions INTEGER,
    purchase_date TIMESTAMPTZ DEFAULT NOW(),
    is_active BOOLEAN DEFAULT TRUE,
    notes TEXT,
    cash_session_id BIGINT,
    payment_method TEXT,
    price DECIMAL(15, 2) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS package_usage_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id BIGINT REFERENCES service_packages(id) ON DELETE CASCADE,
    appointment_id BIGINT,
    used_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Add missing columns to existing tables
ALTER TABLE sales ADD COLUMN IF NOT EXISTS cash_session_id BIGINT REFERENCES cash_sessions(id);

ALTER TABLE beauty_services ADD COLUMN IF NOT EXISTS cash_session_id BIGINT REFERENCES cash_sessions(id);
ALTER TABLE beauty_services ADD COLUMN IF NOT EXISTS payment_method TEXT DEFAULT 'CASH';

ALTER TABLE appointments ADD COLUMN IF NOT EXISTS cash_session_id BIGINT REFERENCES cash_sessions(id);
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS service_id BIGINT;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS service_package_id BIGINT REFERENCES service_packages(id);

-- 3. Open RLS for all tables (Public Access)
DO $$
DECLARE
    t text;
BEGIN
    FOR t IN 
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = 'public' 
    LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('DROP POLICY IF EXISTS "Allow Public Access" ON %I', t);
        EXECUTE format('CREATE POLICY "Allow Public Access" ON %I FOR ALL TO public USING (true) WITH CHECK (true)', t);
    END LOOP;
END $$;
