-- MASTER DB SETUP FOR VIDALITA
-- This script correctly initializes ALL tables and sets up PUBLIC access.
-- Copy and run this in Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- ==========================================
-- 1. BASIC TABLES & COLUMNS
-- ==========================================

-- Members
CREATE TABLE IF NOT EXISTS members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname TEXT,
    phone TEXT,
    qrcodeid TEXT UNIQUE,
    joindate TIMESTAMPTZ DEFAULT NOW(),
    gymstart TIMESTAMPTZ,
    gymend TIMESTAMPTZ,
    gymactive INTEGER DEFAULT 1,
    beautyhasrecord INTEGER DEFAULT 0,
    photo TEXT,
    birthdate DATE,
    email TEXT,
    region TEXT,
    district TEXT,
    lastupdated TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Gym Memberships
CREATE TABLE IF NOT EXISTS gym_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memberid BIGINT REFERENCES members(id) ON DELETE CASCADE,
    startdate TIMESTAMPTZ,
    enddate TIMESTAMPTZ,
    membershiptype TEXT,
    active INTEGER DEFAULT 1,
    createdat TIMESTAMPTZ DEFAULT NOW(),
    updatedat TIMESTAMPTZ DEFAULT NOW()
);

-- Gym Info (Health/Emergency)
CREATE TABLE IF NOT EXISTS gym_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memberid BIGINT REFERENCES members(id) ON DELETE CASCADE UNIQUE,
    emergencyname TEXT,
    emergencyphone TEXT,
    emergencyrelation TEXT,
    medicalconditions TEXT,
    medications TEXT,
    fitnessgoals TEXT,
    membershiptype TEXT,
    membershiptypeother TEXT,
    paymentmethod TEXT,
    paymentmethodother TEXT
);

-- Beauty Health Info
CREATE TABLE IF NOT EXISTS beauty_health_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memberid BIGINT REFERENCES members(id) ON DELETE CASCADE UNIQUE,
    bloodpressure TEXT, diabetes TEXT, cancer TEXT, cancerdetails TEXT,
    cancertreatment TEXT, cancertreatmentdetails TEXT, hormonal TEXT,
    thyroid TEXT, skin TEXT, skindetails TEXT, alcohol TEXT, prosthesis TEXT,
    platinum TEXT, implants TEXT, crowns TEXT, surgery TEXT, surgerydetails TEXT,
    surgerydate TIMESTAMPTZ, smoking TEXT, medications TEXT
);

-- Checkins
CREATE TABLE IF NOT EXISTS checkins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memberid BIGINT REFERENCES members(id) ON DELETE CASCADE,
    qrcodeid TEXT,
    date TIMESTAMPTZ DEFAULT NOW(),
    verifiedby TEXT DEFAULT 'system'
);

-- Beauty Services History
CREATE TABLE IF NOT EXISTS beauty_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memberid BIGINT REFERENCES members(id) ON DELETE CASCADE,
    servicetype TEXT,
    servicename TEXT,
    servicedate TIMESTAMPTZ DEFAULT NOW(),
    amount DECIMAL(15, 2) DEFAULT 0,
    discountpercent DECIMAL(5, 2) DEFAULT 0,
    note TEXT,
    cash_session_id BIGINT -- Added for Kassa integration
);

-- ==========================================
-- 2. INVENTORY & POS (KASSA)
-- ==========================================

-- Product Categories
CREATE TABLE IF NOT EXISTS product_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

-- Products
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    brand TEXT,
    category_id BIGINT REFERENCES product_categories(id) ON DELETE SET NULL,
    sku TEXT,
    barcode TEXT,
    unit TEXT DEFAULT 'pcs',
    sale_price DECIMAL(15, 2) DEFAULT 0,
    discount_percent DECIMAL(5, 2) DEFAULT 0,
    cost_price_default DECIMAL(15, 2) DEFAULT 0,
    reorder_level INTEGER DEFAULT 0,
    image_url TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Stock
CREATE TABLE IF NOT EXISTS inventory_stock (
    product_id BIGINT PRIMARY KEY REFERENCES products(id) ON DELETE CASCADE,
    quantity_on_hand INTEGER DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Movements
CREATE TABLE IF NOT EXISTS inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    type TEXT CHECK (type IN ('IN', 'OUT')),
    qty INTEGER NOT NULL,
    unit_cost DECIMAL(15, 2),
    reason TEXT,
    reference_type TEXT, -- e.g., 'sale', 'purchase'
    reference_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- CASH SESSIONS (THIS FIXES THE 404)
CREATE TABLE IF NOT EXISTS cash_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opened_at TIMESTAMPTZ DEFAULT NOW(),
    closed_at TIMESTAMPTZ,
    opened_by TEXT, -- Stores username or UUID
    closed_by TEXT,
    opening_balance DECIMAL(15, 2) DEFAULT 0,
    closing_balance DECIMAL(15, 2),
    status TEXT DEFAULT 'open' CHECK (status IN ('open', 'closed')),
    notes TEXT
);

-- Sales
CREATE TABLE IF NOT EXISTS sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT REFERENCES members(id) ON DELETE SET NULL,
    total_amount DECIMAL(15, 2) NOT NULL,
    discount_amount DECIMAL(15, 2) DEFAULT 0,
    payment_method TEXT,
    payment_status TEXT DEFAULT 'PAID',
    cash_session_id BIGINT REFERENCES cash_sessions(id),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Sale Items
CREATE TABLE IF NOT EXISTS sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT REFERENCES sales(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    qty INTEGER NOT NULL,
    unit_price DECIMAL(15, 2) NOT NULL,
    unit_cost_snapshot DECIMAL(15, 2),
    line_total DECIMAL(15, 2) NOT NULL
);

-- ==========================================
-- 3. APPOINTMENTS & STAFF
-- ==========================================

-- Staff
CREATE TABLE IF NOT EXISTS staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    specialty TEXT,
    is_active BOOLEAN DEFAULT TRUE
);

-- Rooms
CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT
);

-- Service Packages
CREATE TABLE IF NOT EXISTS service_packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
    service_type TEXT,
    service_name TEXT,
    total_sessions INTEGER,
    remaining_sessions INTEGER,
    purchase_date TIMESTAMPTZ DEFAULT NOW(),
    is_active BOOLEAN DEFAULT TRUE,
    notes TEXT
);

-- Package Usage Log
CREATE TABLE IF NOT EXISTS package_usage_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id BIGINT REFERENCES service_packages(id) ON DELETE CASCADE,
    appointment_id BIGINT, -- Links to appointments later
    used_at TIMESTAMPTZ DEFAULT NOW()
);

-- Appointments
CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT REFERENCES members(id) ON DELETE SET NULL,
    guest_name TEXT,
    guest_phone TEXT,
    service_id BIGINT,
    service_name TEXT,
    staff_id BIGINT REFERENCES staff(id),
    room_id BIGINT REFERENCES rooms(id),
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    status TEXT DEFAULT 'BOOKED' CHECK (status IN ('BOOKED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW')),
    price DECIMAL(15, 2) DEFAULT 0,
    discount DECIMAL(15, 2) DEFAULT 0,
    deposit_amount DECIMAL(15, 2) DEFAULT 0,
    service_package_id BIGINT REFERENCES service_packages(id),
    cash_session_id BIGINT REFERENCES cash_sessions(id),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Users (Simple Authentication)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT DEFAULT 'admin'
);

-- ==========================================
-- 4. PUBLIC RLS POLICIES (OPEN ACCESS)
-- ==========================================

DO $$
DECLARE
    t text;
BEGIN
    FOR t IN 
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = 'public' 
    LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('DROP POLICY IF EXISTS "Allow Public Access" ON %I', t);
        EXECUTE format('CREATE POLICY "Allow Public Access" ON %I FOR ALL TO public USING (true) WITH CHECK (true)', t);
    END LOOP;
END $$;
