-- Vidalita loyihasi uchun YAKUNIY RLS va Sxema tuzatish skripti
-- Ushbu skriptni Supabase SQL Editor orqali ishga tushiring.

-- 1. members jadvalidagi RLS ni PUBLIC (hamma) uchun ochish
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all for authenticated users" ON members;
DROP POLICY IF EXISTS "Enable all for public" ON members;
CREATE POLICY "Enable all for public" ON members FOR ALL TO public USING (true) WITH CHECK (true);

-- 2. gym_memberships jadvali
CREATE TABLE IF NOT EXISTS gym_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memberid BIGINT REFERENCES members(id) ON DELETE CASCADE,
    startdate TIMESTAMPTZ,
    enddate TIMESTAMPTZ,
    membershiptype TEXT,
    active INTEGER DEFAULT 1,
    createdat TIMESTAMPTZ DEFAULT NOW(),
    updatedat TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE gym_memberships ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all for authenticated users" ON gym_memberships;
DROP POLICY IF EXISTS "Enable all for public" ON gym_memberships;
CREATE POLICY "Enable all for public" ON gym_memberships FOR ALL TO public USING (true) WITH CHECK (true);

-- 3. gym_info jadvali
CREATE TABLE IF NOT EXISTS gym_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memberid BIGINT REFERENCES members(id) ON DELETE CASCADE UNIQUE,
    emergencyname TEXT,
    emergencyphone TEXT,
    emergencyrelation TEXT,
    medicalconditions TEXT,
    medications TEXT,
    fitnessgoals TEXT,
    membershiptype TEXT,
    membershiptypeother TEXT,
    paymentmethod TEXT,
    paymentmethodother TEXT
);
ALTER TABLE gym_info ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all for authenticated users" ON gym_info;
DROP POLICY IF EXISTS "Enable all for public" ON gym_info;
CREATE POLICY "Enable all for public" ON gym_info FOR ALL TO public USING (true) WITH CHECK (true);

-- 4. beauty_health_info jadvali
CREATE TABLE IF NOT EXISTS beauty_health_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memberid BIGINT REFERENCES members(id) ON DELETE CASCADE UNIQUE,
    bloodpressure TEXT,
    diabetes TEXT,
    cancer TEXT,
    cancerdetails TEXT,
    cancertreatment TEXT,
    cancertreatmentdetails TEXT,
    hormonal TEXT,
    thyroid TEXT,
    skin TEXT,
    skindetails TEXT,
    alcohol TEXT,
    prosthesis TEXT,
    platinum TEXT,
    implants TEXT,
    crowns TEXT,
    surgery TEXT,
    surgerydetails TEXT,
    surgerydate TIMESTAMPTZ,
    smoking TEXT,
    medications TEXT
);
ALTER TABLE beauty_health_info ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all for authenticated users" ON beauty_health_info;
DROP POLICY IF EXISTS "Enable all for public" ON beauty_health_info;
CREATE POLICY "Enable all for public" ON beauty_health_info FOR ALL TO public USING (true) WITH CHECK (true);

-- 5. service_packages jadvali
ALTER TABLE service_packages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all for authenticated users" ON service_packages;
DROP POLICY IF EXISTS "Enable all for public" ON service_packages;
CREATE POLICY "Enable all for public" ON service_packages FOR ALL TO public USING (true) WITH CHECK (true);

-- 6. Boshqa asosiy jadvallar uchun ham RLS ochish (agar yopiq bo'lsa)
ALTER TABLE checkins ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public" ON checkins;
CREATE POLICY "Allow public" ON checkins FOR ALL TO public USING (true) WITH CHECK (true);

ALTER TABLE beauty_services ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public" ON beauty_services;
CREATE POLICY "Allow public" ON beauty_services FOR ALL TO public USING (true) WITH CHECK (true);

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public" ON users;
CREATE POLICY "Allow public" ON users FOR ALL TO public USING (true) WITH CHECK (true);
