-- Vidalita loyihasi uchun barcha kerakli jadvallar va RLS siyosatlari
-- Ushbu skriptni Supabase SQL Editor orqali ishga tushiring.

-- 1. members jadvaliga kerakli ustunlarni qo'shish (agar yo'q bo'lsa)
ALTER TABLE members ADD COLUMN IF NOT EXISTS lastupdated TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE members ADD COLUMN IF NOT EXISTS beautyhasrecord INTEGER DEFAULT 0;
ALTER TABLE members ADD COLUMN IF NOT EXISTS gymactive INTEGER DEFAULT 1;

-- 2. gym_memberships jadvali
CREATE TABLE IF NOT EXISTS gym_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memberid BIGINT REFERENCES members(id) ON DELETE CASCADE,
    startdate TIMESTAMPTZ,
    enddate TIMESTAMPTZ,
    membershiptype TEXT,
    active INTEGER DEFAULT 1,
    createdat TIMESTAMPTZ DEFAULT NOW(),
    updatedat TIMESTAMPTZ DEFAULT NOW()
);

-- 3. gym_info jadvali
CREATE TABLE IF NOT EXISTS gym_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memberid BIGINT REFERENCES members(id) ON DELETE CASCADE UNIQUE,
    emergencyname TEXT,
    emergencyphone TEXT,
    emergencyrelation TEXT,
    medicalconditions TEXT,
    medications TEXT,
    fitnessgoals TEXT,
    membershiptype TEXT,
    membershiptypeother TEXT,
    paymentmethod TEXT,
    paymentmethodother TEXT
);

-- 4. beauty_health_info jadvali
CREATE TABLE IF NOT EXISTS beauty_health_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memberid BIGINT REFERENCES members(id) ON DELETE CASCADE UNIQUE,
    bloodpressure TEXT,
    diabetes TEXT,
    cancer TEXT,
    cancerdetails TEXT,
    cancertreatment TEXT,
    cancertreatmentdetails TEXT,
    hormonal TEXT,
    thyroid TEXT,
    skin TEXT,
    skindetails TEXT,
    alcohol TEXT,
    prosthesis TEXT,
    platinum TEXT,
    implants TEXT,
    crowns TEXT,
    surgery TEXT,
    surgerydetails TEXT,
    surgerydate TIMESTAMPTZ,
    smoking TEXT,
    medications TEXT
);

-- 5. RLS Siyosatlarini faollashtirish
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE gym_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE gym_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE beauty_health_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_packages ENABLE ROW LEVEL SECURITY;

-- 6. Authenticated foydalanuvchilar uchun ruxsatlar (Soddalashtirilgan)
DO $$
BEGIN
    -- members
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable all for authenticated users' AND tablename = 'members') THEN
        CREATE POLICY "Enable all for authenticated users" ON members FOR ALL TO authenticated USING (true);
    END IF;
    -- gym_memberships
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable all for authenticated users' AND tablename = 'gym_memberships') THEN
        CREATE POLICY "Enable all for authenticated users" ON gym_memberships FOR ALL TO authenticated USING (true);
    END IF;
    -- gym_info
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable all for authenticated users' AND tablename = 'gym_info') THEN
        CREATE POLICY "Enable all for authenticated users" ON gym_info FOR ALL TO authenticated USING (true);
    END IF;
    -- beauty_health_info
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable all for authenticated users' AND tablename = 'beauty_health_info') THEN
        CREATE POLICY "Enable all for authenticated users" ON beauty_health_info FOR ALL TO authenticated USING (true);
    END IF;
END $$;
