-- Go'zallik xizmati seanslarini (paketlar) boshqarish tizimi
-- Ushbu SQL skriptini Supabase SQL Editor orqali ishga tushiring.

CREATE TABLE IF NOT EXISTS service_packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
    service_type TEXT NOT NULL,
    service_name TEXT NOT NULL,
    total_sessions INTEGER NOT NULL,
    remaining_sessions INTEGER NOT NULL,
    purchase_date TIMESTAMPTZ DEFAULT NOW(),
    is_active BOOLEAN DEFAULT TRUE,
    notes TEXT
);

-- RLS (Row Level Security) - Supabase'da ma'lumotlarni ko'rish va yozish uchun ruxsat berish
ALTER TABLE service_packages ENABLE ROW LEVEL SECURITY;

-- Barcha foydalanuvchilarga (authenticated) ruxsat berish
CREATE POLICY "Enable all for authenticated users" ON service_packages FOR ALL TO authenticated USING (true);
