-- Kassa sessiyalari va Seansli xizmatlar uchun qo'shimcha jadvallar

-- 1. Kassa sessiyalari jadvali
CREATE TABLE IF NOT EXISTS cash_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opened_at TIMESTAMPTZ DEFAULT NOW(),
    closed_at TIMESTAMPTZ,
    opened_by UUID REFERENCES auth.users(id),
    closed_by UUID REFERENCES auth.users(id),
    opening_balance DECIMAL(15, 2) DEFAULT 0,
    closing_balance DECIMAL(15, 2),
    status TEXT DEFAULT 'open' CHECK (status IN ('open', 'closed')),
    notes TEXT
);

-- 2. Sales va Beauty Services jadvaliga kassa sessiyasini bog'lash
ALTER TABLE sales ADD COLUMN IF NOT EXISTS cash_session_id BIGINT REFERENCES cash_sessions(id);
ALTER TABLE beauty_services ADD COLUMN IF NOT EXISTS cash_session_id BIGINT REFERENCES cash_sessions(id);

-- 3. Appointments jadvaliga paketni bog'lash
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS service_package_id BIGINT REFERENCES service_packages(id);

-- 4. service_packages jadvaliga qo'shimcha ustunlar
ALTER TABLE service_packages ADD COLUMN IF NOT EXISTS session_interval INTEGER; -- kunlar hisobida
ALTER TABLE service_packages ADD COLUMN IF NOT EXISTS price_per_session DECIMAL(15, 2);

-- 5. Seanslardan foydalanish logi
CREATE TABLE IF NOT EXISTS package_usage_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id BIGINT REFERENCES service_packages(id) ON DELETE CASCADE,
    appointment_id BIGINT REFERENCES appointments(id) ON DELETE SET NULL,
    used_at TIMESTAMPTZ DEFAULT NOW(),
    notes TEXT
);

-- RLS
ALTER TABLE cash_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE package_usage_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated users" ON cash_sessions FOR ALL TO authenticated USING (true);
CREATE POLICY "Enable all for authenticated users" ON package_usage_log FOR ALL TO authenticated USING (true);
