-- Appointment Booking Schema for Vidalita

-- 1. Staff
CREATE TABLE IF NOT EXISTS staff (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name TEXT NOT NULL,
    role TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    working_hours_json JSONB, -- Store weekly schedule
    photo_url TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 2. Rooms (Optional rooms/cabins management)
CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 3. Appointments
CREATE TABLE IF NOT EXISTS appointments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    member_id BIGINT REFERENCES members(id) ON DELETE SET NULL,
    guest_name TEXT, -- For non-members
    guest_phone TEXT,
    service_id BIGINT REFERENCES beauty_services(id), -- Or a separate services table if redefined
    service_name TEXT,
    staff_id BIGINT REFERENCES staff(id) ON DELETE SET NULL,
    room_id BIGINT REFERENCES rooms(id) ON DELETE SET NULL,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    status TEXT CHECK (status IN ('BOOKED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW')) DEFAULT 'BOOKED',
    price NUMERIC(15, 2) NOT NULL,
    discount NUMERIC(15, 2) DEFAULT 0,
    deposit_amount NUMERIC(15, 2) DEFAULT 0,
    notes TEXT,
    created_by BIGINT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Add optional service_name column if table already exists
ALTER TABLE IF EXISTS appointments
    ADD COLUMN IF NOT EXISTS service_name TEXT;

-- 4. Appointment Payments (For deposit tracking or linking to sales)
CREATE TABLE IF NOT EXISTS appointment_payments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    appointment_id UUID REFERENCES appointments(id) ON DELETE CASCADE,
    amount NUMERIC(15, 2) NOT NULL,
    method TEXT, -- CASH, CARD, etc.
    payment_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_appointments_staff_time ON appointments(staff_id, start_time, end_time);
CREATE INDEX IF NOT EXISTS idx_appointments_member ON appointments(member_id);
CREATE INDEX IF NOT EXISTS idx_appointments_status ON appointments(status);
CREATE INDEX IF NOT EXISTS idx_appointments_time ON appointments(start_time);
