-- POS & Inventory Schema for Vidalita

-- 1. Product Categories
CREATE TABLE IF NOT EXISTS product_categories (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 2. Products
CREATE TABLE IF NOT EXISTS products (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    brand TEXT,
    category_id BIGINT REFERENCES product_categories(id) ON DELETE SET NULL,
    sku TEXT UNIQUE,
    barcode TEXT UNIQUE,
    unit TEXT DEFAULT 'pcs', -- pcs, ml, etc.
    sale_price NUMERIC(15, 2) NOT NULL DEFAULT 0,
    cost_price_default NUMERIC(15, 2) DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    reorder_level INTEGER DEFAULT 5,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 3. Inventory Stock (Current snapshot)
CREATE TABLE IF NOT EXISTS inventory_stock (
    product_id BIGINT PRIMARY KEY REFERENCES products(id) ON DELETE CASCADE,
    quantity_on_hand INTEGER DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 4. Inventory Movements (Audit trail)
CREATE TABLE IF NOT EXISTS inventory_movements (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    type TEXT CHECK (type IN ('IN', 'OUT', 'ADJUST')),
    qty INTEGER NOT NULL,
    unit_cost NUMERIC(15, 2), -- Cost at time of entry
    reason TEXT, -- purchase, sale, damage, return, adjustment
    reference_type TEXT, -- sale, purchase, refund
    reference_id UUID, -- For linking to specific transactions
    created_by BIGINT, -- references users(id) if needed
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 5. Sales (Header)
CREATE TABLE IF NOT EXISTS sales (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    member_id BIGINT REFERENCES members(id) ON DELETE SET NULL,
    total_amount NUMERIC(15, 2) NOT NULL,
    discount_amount NUMERIC(15, 2) DEFAULT 0,
    tax_amount NUMERIC(15, 2) DEFAULT 0,
    payment_status TEXT CHECK (payment_status IN ('PAID', 'PARTIAL', 'UNPAID')) DEFAULT 'PAID',
    payment_method TEXT, -- CASH, CARD, MIXED, ONLINE
    notes TEXT,
    created_by BIGINT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 6. Sale Items (Detail)
CREATE TABLE IF NOT EXISTS sale_items (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sale_id UUID REFERENCES sales(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id),
    qty INTEGER NOT NULL,
    unit_price NUMERIC(15, 2) NOT NULL,
    unit_cost_snapshot NUMERIC(15, 2), -- For margin calculation later
    line_total NUMERIC(15, 2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 7. Refunds
CREATE TABLE IF NOT EXISTS refunds (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sale_id UUID REFERENCES sales(id) ON DELETE CASCADE,
    total_refund NUMERIC(15, 2) NOT NULL,
    reason TEXT,
    created_by BIGINT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 8. Refund Items
CREATE TABLE IF NOT EXISTS refund_items (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    refund_id UUID REFERENCES refunds(id) ON DELETE CASCADE,
    sale_item_id BIGINT REFERENCES sale_items(id),
    qty INTEGER NOT NULL,
    amount NUMERIC(15, 2) NOT NULL,
    restock BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX idx_products_sku ON products(sku);
CREATE INDEX idx_products_barcode ON products(barcode);
CREATE INDEX idx_inventory_movements_product ON inventory_movements(product_id);
CREATE INDEX idx_sales_member ON sales(member_id);
CREATE INDEX idx_sales_date ON sales(created_at);
CREATE INDEX idx_sale_items_sale ON sale_items(sale_id);
