-- 0. SCHEMA INITIALIZATION
-- This file contains the complete database structure for Vidalita Gym & Beauty.
-- IMPORTANT: Do not run standard 'DROP TABLE' commands if you want to keep existing data.

-- 1. MEMBERS
CREATE TABLE IF NOT EXISTS members (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  fullname TEXT,
  phone TEXT,
  gender TEXT,
  qrcodeid TEXT UNIQUE,
  joindate TEXT,
  gymstart TEXT,
  gymend TEXT,
  gymactive INTEGER DEFAULT 0,
  beautyhasrecord INTEGER DEFAULT 0,
  lastupdated TEXT,
  synced INTEGER DEFAULT 0,
  photo TEXT,
  birthdate TEXT,
  email TEXT,
  region TEXT,
  district TEXT
);

-- 2. CHECKINS
CREATE TABLE IF NOT EXISTS checkins (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  memberid BIGINT REFERENCES members(id) ON DELETE CASCADE,
  qrcodeid TEXT,
  date TEXT,
  verifiedby TEXT,
  synced INTEGER DEFAULT 0
);

-- 3. BEAUTY_SERVICES
CREATE TABLE IF NOT EXISTS beauty_services (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  memberid BIGINT REFERENCES members(id) ON DELETE CASCADE,
  servicename TEXT,
  servicetype TEXT,
  servicedate TEXT,
  note TEXT,
  amount REAL DEFAULT 0,
  paymentstatus TEXT DEFAULT 'pending',
  paymentmethod TEXT,
  paymentdate TEXT,
  discountpercent REAL DEFAULT 0
);

-- 4. BEAUTY_HEALTH_INFO
CREATE TABLE IF NOT EXISTS beauty_health_info (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  memberid BIGINT UNIQUE REFERENCES members(id) ON DELETE CASCADE,
  bloodpressure TEXT,
  diabetes TEXT,
  cancer TEXT,
  cancerdetails TEXT,
  cancertreatment TEXT,
  cancertreatmentdetails TEXT,
  hormonal TEXT,
  thyroid TEXT,
  skin TEXT,
  skindetails TEXT,
  alcohol TEXT,
  prosthesis TEXT,
  platinum TEXT,
  implants TEXT,
  crowns TEXT,
  surgery TEXT,
  surgerydetails TEXT,
  surgerydate TEXT,
  smoking TEXT,
  medications TEXT
);

-- 5. GYM_INFO
CREATE TABLE IF NOT EXISTS gym_info (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  memberid BIGINT UNIQUE REFERENCES members(id) ON DELETE CASCADE,
  emergencyname TEXT,
  emergencyphone TEXT,
  emergencyrelation TEXT,
  medicalconditions TEXT,
  medications TEXT,
  fitnessgoals TEXT,
  membershiptype TEXT,
  membershiptypeother TEXT,
  paymentmethod TEXT,
  paymentmethodother TEXT
);

-- 6. GYM_PAYMENTS
CREATE TABLE IF NOT EXISTS gym_payments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  memberid BIGINT REFERENCES members(id) ON DELETE CASCADE,
  amount REAL NOT NULL,
  paymentdate TEXT NOT NULL,
  periodstart TEXT NOT NULL,
  periodend TEXT NOT NULL,
  paymentmethod TEXT,
  paymentstatus TEXT DEFAULT 'paid',
  note TEXT,
  createdat TEXT DEFAULT CURRENT_TIMESTAMP
);

-- 7. GYM_MEMBERSHIPS
CREATE TABLE IF NOT EXISTS gym_memberships (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  memberid BIGINT REFERENCES members(id) ON DELETE CASCADE,
  startdate TEXT NOT NULL,
  enddate TEXT,
  membershiptype TEXT,
  active INTEGER DEFAULT 1,
  createdat TEXT DEFAULT CURRENT_TIMESTAMP,
  updatedat TEXT DEFAULT CURRENT_TIMESTAMP
);

-- 8. USERS
CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'admin',
  createdat TEXT DEFAULT CURRENT_TIMESTAMP,
  lastlogin TEXT
);

-- Indexlar
CREATE INDEX IF NOT EXISTS idx_members_qrcodeid ON members(qrcodeid);
CREATE INDEX IF NOT EXISTS idx_members_fullname ON members(fullname);
CREATE INDEX IF NOT EXISTS idx_members_phone ON members(phone);
CREATE INDEX IF NOT EXISTS idx_members_gymactive ON members(gymactive);
CREATE INDEX IF NOT EXISTS idx_members_lastupdated ON members(lastupdated);
CREATE INDEX IF NOT EXISTS idx_checkins_memberid ON checkins(memberid);
CREATE INDEX IF NOT EXISTS idx_checkins_date ON checkins(date);
CREATE INDEX IF NOT EXISTS idx_beauty_services_memberid ON beauty_services(memberid);
CREATE INDEX IF NOT EXISTS idx_beauty_services_date ON beauty_services(servicedate);
CREATE INDEX IF NOT EXISTS idx_gym_payments_memberid ON gym_payments(memberid);
CREATE INDEX IF NOT EXISTS idx_gym_payments_date ON gym_payments(paymentdate);
CREATE INDEX IF NOT EXISTS idx_gym_memberships_memberid ON gym_memberships(memberid);
CREATE INDEX IF NOT EXISTS idx_gym_memberships_active_date ON gym_memberships(active, enddate);


-- 9. STORAGE BUCKETS (Execute this in Supabase SQL Editor)
-- First: Go to Storage in Supabase UI and create a PUBLIC bucket named 'member-photos'
-- Then: Run these policies to allow uploads/access without Supabase Auth

/*
-- Allow public access to view images
CREATE POLICY "Public View" ON storage.objects FOR SELECT USING (bucket_id = 'member-photos');

-- Allow anonymous uploads (since we use custom auth)
CREATE POLICY "Anon Upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'member-photos');

-- Allow anonymous updates
CREATE POLICY "Anon Update" ON storage.objects FOR UPDATE USING (bucket_id = 'member-photos');

-- Allow anonymous deletes
CREATE POLICY "Anon Delete" ON storage.objects FOR DELETE USING (bucket_id = 'member-photos');
*/
-- 10. INITIAL DATA (Admin User)
/*
INSERT INTO users (username, password, role) 
VALUES ('admin', 'admin123', 'admin') 
ON CONFLICT (username) DO NOTHING;
*/

-- 11. ROBUST STORAGE SETUP (Run this in SQL Editor to fix upload errors)
/*
-- 1. Create the bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('member-photos', 'member-photos', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- 2. Create policies for anonymous access
-- Note: We use 'true' for check to allow all operations on this specific bucket

-- A. Allow Public to see photos
DROP POLICY IF EXISTS "Public View" ON storage.objects;
CREATE POLICY "Public View" ON storage.objects FOR SELECT 
USING (bucket_id = 'member-photos');

-- B. Allow anyone to upload (Anon included)
DROP POLICY IF EXISTS "Anon Upload" ON storage.objects;
CREATE POLICY "Anon Upload" ON storage.objects FOR INSERT 
WITH CHECK (bucket_id = 'member-photos');

-- C. Allow anyone to update
DROP POLICY IF EXISTS "Anon Update" ON storage.objects;
CREATE POLICY "Anon Update" ON storage.objects FOR UPDATE 
USING (bucket_id = 'member-photos');

-- D. Allow anyone to delete
DROP POLICY IF EXISTS "Anon Delete" ON storage.objects;
CREATE POLICY "Anon Delete" ON storage.objects FOR DELETE 
USING (bucket_id = 'member-photos');
*/
