// Beauty xizmatlar turlari - Enum
// Bu fayl barcha mavjud xizmat turlarini belgilaydi

export const BEAUTY_SERVICE_TYPES = {
  // ============================================
  // ЛАЗЕРНЫЕ ПРОЦЕДУРЫ (Laser Procedures)
  // ============================================
  // Золотая Игла
  GOLDEN_NEEDLE_ACNE_TREATMENT: 'golden_needle_acne_treatment',
  GOLDEN_NEEDLE_WRINKLE_TREATMENT: 'golden_needle_wrinkle_treatment',
  GOLDEN_NEEDLE_BURN_SCAR_TREATMENT: 'golden_needle_burn_scar_treatment',
  GOLDEN_NEEDLE_PIGMENT_SPOT_TREATMENT: 'golden_needle_pigment_spot_treatment',
  GOLDEN_NEEDLE_STRETCH_MARK_TREATMENT: 'golden_needle_stretch_mark_treatment',
  GOLDEN_NEEDLE_ACNE_SCAR_TREATMENT: 'golden_needle_acne_scar_treatment',
  GOLDEN_NEEDLE_SKIN_REJUVENATION: 'golden_needle_skin_rejuvenation',
  GOLDEN_NEEDLE_PORE_TIGHTENING: 'golden_needle_pore_tightening',
  
  // BBL Лазер
  BBL_LASER_FRECKLE_TREATMENT: 'bbl_laser_freckle_treatment',
  BBL_LASER_MELASMA_TREATMENT: 'bbl_laser_melasma_treatment',
  BBL_LASER_PIGMENT_SPOT_TREATMENT: 'bbl_laser_pigment_spot_treatment',
  BBL_LASER_REDNESS_TREATMENT: 'bbl_laser_redness_treatment',
  BBL_LASER_ENLARGED_PORE_TREATMENT: 'bbl_laser_enlarged_pore_treatment',
  BBL_LASER_BIRTHMARK_TREATMENT: 'bbl_laser_birthmark_treatment',
  BBL_LASER_ROSACEA_TREATMENT: 'bbl_laser_rosacea_treatment',
  
  // ND YAG Лазер
  ND_YAG_CARBON_PEELING: 'nd_yag_carbon_peeling',
  ND_YAG_BROW_TATTOO_REMOVAL: 'nd_yag_brow_tattoo_removal',
  ND_YAG_TATTOO_REMOVAL: 'nd_yag_tattoo_removal',
  
  // Фракционный Лазер
  FRACTIONAL_LASER_VAGINAL_TIGHTENING: 'fractional_laser_vaginal_tightening',
  FRACTIONAL_LASER_WRINKLE_TREATMENT: 'fractional_laser_wrinkle_treatment',
  FRACTIONAL_LASER_BURN_SCAR_TREATMENT: 'fractional_laser_burn_scar_treatment',
  FRACTIONAL_LASER_PIGMENT_SPOT_TREATMENT: 'fractional_laser_pigment_spot_treatment',
  FRACTIONAL_LASER_POST_SURGICAL_SCAR_TREATMENT: 'fractional_laser_post_surgical_scar_treatment',
  FRACTIONAL_LASER_STRETCH_MARK_TREATMENT: 'fractional_laser_stretch_mark_treatment',
  FRACTIONAL_LASER_SCAR_TREATMENT: 'fractional_laser_scar_treatment',
  FRACTIONAL_LASER_SUN_SPOT_TREATMENT: 'fractional_laser_sun_spot_treatment',
  
  // Coolite Pro Лазер
  COOLITE_PRO_UPPER_LIP: 'coolite_pro_upper_lip',
  COOLITE_PRO_UPPER_THIGH: 'coolite_pro_upper_thigh',
  COOLITE_PRO_UPPER_ARM: 'coolite_pro_upper_arm',
  COOLITE_PRO_FULL_FACE: 'coolite_pro_full_face',
  COOLITE_PRO_FULL_LEGS: 'coolite_pro_full_legs',
  COOLITE_PRO_FULL_BODY: 'coolite_pro_full_body',
  COOLITE_PRO_FULL_ARM: 'coolite_pro_full_arm',
  COOLITE_PRO_CHEST: 'coolite_pro_chest',
  COOLITE_PRO_NAPE: 'coolite_pro_nape',
  COOLITE_PRO_FOREHEAD: 'coolite_pro_forehead',
  COOLITE_PRO_LOWER_THIGH: 'coolite_pro_lower_thigh',
  COOLITE_PRO_LOWER_ARM: 'coolite_pro_lower_arm',
  COOLITE_PRO_LOWER_BUTTOCKS: 'coolite_pro_lower_buttocks',
  COOLITE_PRO_PERINEAL: 'coolite_pro_perineal',
  COOLITE_PRO_CHIN: 'coolite_pro_chin',
  COOLITE_PRO_ARMPITS: 'coolite_pro_armpits',
  COOLITE_PRO_BUTTOCKS: 'coolite_pro_buttocks',
  COOLITE_PRO_LOWER_BACK: 'coolite_pro_lower_back',
  COOLITE_PRO_ARM: 'coolite_pro_arm',
  COOLITE_PRO_BACK: 'coolite_pro_back',
  COOLITE_PRO_FEET: 'coolite_pro_feet',
  COOLITE_PRO_MUSTACHE: 'coolite_pro_mustache',
  COOLITE_PRO_NECK: 'coolite_pro_neck',
  
  // ============================================
  // ПОХУДЕНИЕ И КОРРЕКЦИЯ ФИГУРЫ (Body Shaping)
  // ============================================
  SHAPE_SMART_LOCAL_WEIGHT_LOSS: 'shape_smart_local_weight_loss',
  SHAPE_SMART_THIGHS: 'shape_smart_thighs',
  SHAPE_SMART_UPPER_THIGHS: 'shape_smart_upper_thighs',
  SHAPE_SMART_ABDOMEN: 'shape_smart_abdomen',
  SHAPE_SMART_FACE_LIFT: 'shape_smart_face_lift',
  SHAPE_SMART_LOWER_THIGHS: 'shape_smart_lower_thighs',
  SHAPE_SMART_CHIN: 'shape_smart_chin',
  SHAPE_SMART_LOWER_BACK: 'shape_smart_lower_back',
  SHAPE_SMART_ARMS: 'shape_smart_arms',
  SHAPE_SMART_BACK: 'shape_smart_back',
  
  // ============================================
  // ЭПИЛЯЦИЯ (Depilation)
  // ============================================
  // Лазерная Эпиляция
  LASER_DEPILATION_SIDEBURNS: 'laser_depilation_sideburns',
  LASER_DEPILATION_THIGHS: 'laser_depilation_thighs',
  LASER_DEPILATION_UPPER_LIP: 'laser_depilation_upper_lip',
  LASER_DEPILATION_UPPER_ARMS: 'laser_depilation_upper_arms',
  LASER_DEPILATION_UPPER_BUTTOCKS: 'laser_depilation_upper_buttocks',
  LASER_DEPILATION_FULL_FACE: 'laser_depilation_full_face',
  LASER_DEPILATION_FULL_LEGS: 'laser_depilation_full_legs',
  LASER_DEPILATION_FULL_ARMS: 'laser_depilation_full_arms',
  LASER_DEPILATION_FULL_BODY: 'laser_depilation_full_body',
  LASER_DEPILATION_GENITAL: 'laser_depilation_genital',
  LASER_DEPILATION_SHINS: 'laser_depilation_shins',
  LASER_DEPILATION_CHEST: 'laser_depilation_chest',
  LASER_DEPILATION_ABDOMEN: 'laser_depilation_abdomen',
  LASER_DEPILATION_NAPE: 'laser_depilation_nape',
  LASER_DEPILATION_HANDS: 'laser_depilation_hands',
  LASER_DEPILATION_FOREHEAD: 'laser_depilation_forehead',
  LASER_DEPILATION_LOWER_ARMS: 'laser_depilation_lower_arms',
  LASER_DEPILATION_CHIN: 'laser_depilation_chin',
  LASER_DEPILATION_ARMPITS: 'laser_depilation_armpits',
  LASER_DEPILATION_LOWER_BACK: 'laser_depilation_lower_back',
  LASER_DEPILATION_BACK: 'laser_depilation_back',
  LASER_DEPILATION_FEET: 'laser_depilation_feet',
  LASER_DEPILATION_NECK: 'laser_depilation_neck',
  LASER_DEPILATION_BUTTOCKS: 'laser_depilation_buttocks',
  
  // Восковая депиляция
  WAX_DEPILATION_FULL_FACE: 'wax_depilation_full_face',
  WAX_DEPILATION_GENITAL: 'wax_depilation_genital',
  WAX_DEPILATION_PACKAGE: 'wax_depilation_package',
  WAX_DEPILATION_ARMPITS: 'wax_depilation_armpits',
  WAX_DEPILATION_FULL_ARM: 'wax_depilation_full_arm',
  WAX_DEPILATION_FULL_LEGS: 'wax_depilation_full_legs',
  WAX_DEPILATION_HALF_LEG: 'wax_depilation_half_leg',
  WAX_DEPILATION_HALF_ARM: 'wax_depilation_half_arm',
  WAX_DEPILATION_LOWER_BACK: 'wax_depilation_lower_back',
  WAX_DEPILATION_BACK: 'wax_depilation_back',
  WAX_DEPILATION_MUSTACHE: 'wax_depilation_mustache',
  WAX_DEPILATION_BUTTOCKS: 'wax_depilation_buttocks',
  
  // Игольчатая Эпиляция
  NEEDLE_DEPILATION: 'needle_depilation',
  
  // ============================================
  // МАССАЖ (Massage)
  // ============================================
  // G8 Массаж
  G8_MASSAGE: 'g8_massage',
  G8_MASSAGE_THIGHS: 'g8_massage_thighs',
  G8_MASSAGE_UPPER_THIGHS: 'g8_massage_upper_thighs',
  G8_MASSAGE_ABDOMEN: 'g8_massage_abdomen',
  G8_MASSAGE_LOWER_THIGHS: 'g8_massage_lower_thighs',
  G8_MASSAGE_LOWER_BACK: 'g8_massage_lower_back',
  G8_MASSAGE_BACK: 'g8_massage_back',
  
  // Endo Roller Массаж
  ENDO_ROLLER_MASSAGE_UPPER_THIGHS: 'endo_roller_massage_upper_thighs',
  ENDO_ROLLER_MASSAGE_LOWER_THIGHS: 'endo_roller_massage_lower_thighs',
  ENDO_ROLLER_MASSAGE_LOWER_BACK: 'endo_roller_massage_lower_back',
  ENDO_ROLLER_MASSAGE_BACK: 'endo_roller_massage_back',
  
  // EMS Slim
  EMS_SLIM_THIGHS: 'ems_slim_thighs',
  EMS_SLIM_UPPER_THIGHS: 'ems_slim_upper_thighs',
  EMS_SLIM_ABDOMEN: 'ems_slim_abdomen',
  
  // Другие массажи
  CLASSICAL_BODY_MASSAGE: 'classical_body_massage',
  LYMPHODRAINAGE: 'lymphodrainage',
  LYMPHODRAINAGE_FREE: 'lymphodrainage_free',
  LYMPHODRAINAGE_8: 'lymphodrainage_8',
  LYMPHODRAINAGE_FULL_BODY: 'lymphodrainage_full_body',
  HAIR_MASSAGE_CARE: 'hair_massage_care',
  PASSIVE_GYMNASTICS: 'passive_gymnastics',
  PASSIVE_GYMNASTICS_1: 'passive_gymnastics_1',
  PASSIVE_GYMNASTICS_FREE: 'passive_gymnastics_free',
  PASSIVE_GYMNASTICS_8: 'passive_gymnastics_8',
  
  // ============================================
  // УХОД ЗА ЛИЦОМ (Facial Care)
  // ============================================
  HYDRAMASTER_BREAST_LIFT: 'hydramaster_breast_lift',
  HYDRAMASTER_BUTTOCKS_LIFT: 'hydramaster_buttocks_lift',
  HYDRAMASTER_FACIAL_CARE: 'hydramaster_facial_care',
  HIFU_FACE_LIFT: 'hifu_face_lift',
  HIFU_CHIN_LIFT: 'hifu_chin_lift',
  HIFU_SKIN_REJUVENATION: 'hifu_skin_rejuvenation',
  HIFU_BROW_LIFT: 'hifu_brow_lift',
  HIFU_WRINKLE_REDUCTION: 'hifu_wrinkle_reduction',
  CLASSICAL_FACIAL_CARE: 'classical_facial_care',
  
  // ============================================
  // УСЛУГИ ДЛЯ НОГТЕЙ (Nail Services)
  // ============================================
  NAIL_POLISH: 'nail_polish',
  MANICURE: 'manicure',
  PEDICURE: 'pedicure',
  NAIL_EXTENSION: 'nail_extension',
  PLASTIC_NAILS: 'plastic_nails',
  HEEL_CARE: 'heel_care',
  HENNA_NAILS: 'henna_nails',
  SHELLAC: 'shellac',
  MANICURE_FEET: 'manicure_feet',
  
  // ============================================
  // ФИТНЕС (Fitness)
  // ============================================
  ZUMBA_MONTHLY: 'zumba_monthly',
  ZUMBA_CLASS: 'zumba_class',
  YOGA_MONTHLY: 'yoga_monthly',
  PILATES_GROUP: 'pilates_group',
  PILATES_INDIVIDUAL: 'pilates_individual',
  SPORTS_NUTRITION_PLANNING: 'sports_nutrition_planning',
  FITNESS_12_MONTHS: 'fitness_12_months',
  FITNESS_3_MONTHS: 'fitness_3_months',
  FITNESS_6_MONTHS: 'fitness_6_months',
  
  // ============================================
  // СТАРЫЕ УСЛУГИ (Old Services - для совместимости)
  // ============================================
  HAIRCUT: 'haircut',
  HAIR_COLORING: 'hair_coloring',
  HAIR_STYLING: 'hair_styling',
  HAIR_TREATMENT: 'hair_treatment',
  HAIR_EXTENSION: 'hair_extension',
  FACIAL: 'facial',
  CLEANING: 'cleaning',
  PEELING: 'peeling',
  MASK: 'mask',
  MICRODERMABRASION: 'microdermabrasion',
  EYEBROW: 'eyebrow',
  EYELASH: 'eyelash',
  EYELASH_EXTENSION: 'eyelash_extension',
  BODY_MASSAGE: 'body_massage',
  BODY_WRAP: 'body_wrap',
  BODY_SCRUB: 'body_scrub',
  DEPILATION: 'depilation',
  NAIL_ART: 'nail_art',
  GEL_NAILS: 'gel_nails',
  MAKEUP: 'makeup',
  BRIDAL_MAKEUP: 'bridal_makeup',
  EVENT_MAKEUP: 'event_makeup',
  CONSULTATION: 'consultation',
  OTHER: 'other'
}

// Xizmat turlarini ko'rsatish uchun (frontend'da ishlatish) - Rus tilida
export const BEAUTY_SERVICE_LABELS = {
  // Лазерные процедуры
  [BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_ACNE_TREATMENT]: 'Золотая Игла Лечение Акне (3 Сеанса)',
  [BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_WRINKLE_TREATMENT]: 'Золотая Игла Лечение Морщин (3 Сеанса)',
  [BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_BURN_SCAR_TREATMENT]: 'Золотая Игла Лечение Ожоговых Шрамов (3 Сеанса)',
  [BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_PIGMENT_SPOT_TREATMENT]: 'Золотая Игла Лечение Пигментных Пятен (3 Сеанса)',
  [BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_STRETCH_MARK_TREATMENT]: 'Золотая Игла Лечение Растяжек Кожи',
  [BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_ACNE_SCAR_TREATMENT]: 'Золотая Игла Лечение Шрамов От Прыщей (3 Сеанса)',
  [BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_SKIN_REJUVENATION]: 'Золотая Игла Омоложение Кожи',
  [BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_PORE_TIGHTENING]: 'Золотая Игла Сужение Пор (3 Сеанса)',
  
  [BEAUTY_SERVICE_TYPES.BBL_LASER_FRECKLE_TREATMENT]: 'BBL Лазер Лечение Веснушек (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.BBL_LASER_MELASMA_TREATMENT]: 'BBL Лазер Лечение Мелазмы (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.BBL_LASER_PIGMENT_SPOT_TREATMENT]: 'BBL Лазер Лечение Пигментных Пятен (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.BBL_LASER_REDNESS_TREATMENT]: 'BBL Лазер Лечение Покраснений Кожи (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.BBL_LASER_ENLARGED_PORE_TREATMENT]: 'BBL Лазер Лечение Расширенных Пор (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.BBL_LASER_BIRTHMARK_TREATMENT]: 'BBL Лазер Лечение Родимых Пятен (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.BBL_LASER_ROSACEA_TREATMENT]: 'BBL Лазер Лечение Розацеа (1 Сеанс)',
  
  [BEAUTY_SERVICE_TYPES.ND_YAG_CARBON_PEELING]: 'ND YAG Лазер Карбоновый Пилинг',
  [BEAUTY_SERVICE_TYPES.ND_YAG_BROW_TATTOO_REMOVAL]: 'ND YAG Лазер Удаление Татуажа Бровей (3 Сеанса)',
  [BEAUTY_SERVICE_TYPES.ND_YAG_TATTOO_REMOVAL]: 'ND YAG Лазер Удаление Татуировки (8 Сеансов)',
  
  [BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_VAGINAL_TIGHTENING]: 'Фракционный Лазер Вагинальное Сужение И Лечение Недержания Мочи',
  [BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_WRINKLE_TREATMENT]: 'Фракционный Лазер Лечение Морщин (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_BURN_SCAR_TREATMENT]: 'Фракционный Лазер Лечение Ожоговых Шрамов (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_PIGMENT_SPOT_TREATMENT]: 'Фракционный Лазер Лечение Пигментных Пятен (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_POST_SURGICAL_SCAR_TREATMENT]: 'Фракционный Лазер Лечение Послеоперационных Шрамов (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_STRETCH_MARK_TREATMENT]: 'Фракционный Лазер Лечение Растяжек (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_SCAR_TREATMENT]: 'Фракционный Лазер Лечение Рубцов (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_SUN_SPOT_TREATMENT]: 'Фракционный Лазер Лечение Солнечных Пятен (1 Сеанс)',
  
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_UPPER_LIP]: 'Coolite Pro Лазер Верхняя губа (Один сеанс)',
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_UPPER_THIGH]: 'Coolite Pro Лазер Верхняя часть бедра (Один сеанс)',
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_UPPER_ARM]: 'Coolite Pro Лазер Верхняя часть руки (Один сеанс)',
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_FULL_FACE]: 'Coolite Pro Лазер Все лицо (Один сеанс)',
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_FULL_LEGS]: 'Coolite Pro Лазер Все ноги (Один сеанс)',
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_FULL_BODY]: 'Coolite Pro Лазер Все тело: подмышки, гениталии, все ноги (6 сеансов)',
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_FULL_ARM]: 'Coolite Pro Лазер Вся рука (Один сеанс)',
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_CHEST]: 'Coolite Pro Лазер Грудь (Один сеанс)',
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_NAPE]: 'Coolite Pro Лазер Затылок (Один сеанс)',
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_FOREHEAD]: 'Coolite Pro Лазер Лоб (Один сеанс)',
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_LOWER_THIGH]: 'Coolite Pro Лазер Нижняя часть бедра (Один сеанс)',
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_LOWER_ARM]: 'Coolite Pro Лазер Нижняя часть руки (Один сеанс)',
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_LOWER_BUTTOCKS]: 'Coolite Pro Лазер Нижняя часть ягодиц (Один сеанс)',
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_PERINEAL]: 'Coolite Pro Лазер Перинальная зона (Один сеанс)',
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_CHIN]: 'Coolite Pro Лазер Подбородок (Один сеанс)',
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_ARMPITS]: 'Coolite Pro Лазер Подмышки (Один сеанс)',
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_BUTTOCKS]: 'Coolite Pro Лазер Попа (Один сеанс)',
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_LOWER_BACK]: 'Coolite Pro Лазер Поясница (Один сеанс)',
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_ARM]: 'Coolite Pro Лазер Рука (Один сеанс)',
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_BACK]: 'Coolite Pro Лазер Спина (Один сеанс)',
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_FEET]: 'Coolite Pro Лазер Ступни (Один сеанс)',
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_MUSTACHE]: 'Coolite Pro Лазер Усики (Один сеанс)',
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_NECK]: 'Coolite Pro Лазер Шея (Один сеанс)',
  
  // Похудение
  [BEAUTY_SERVICE_TYPES.SHAPE_SMART_LOCAL_WEIGHT_LOSS]: 'Shape Smart Локальное Похудение (8 Сеансов)',
  [BEAUTY_SERVICE_TYPES.SHAPE_SMART_THIGHS]: 'Shape Smart Локальное Похудение Бёдра (8 Сеансов)',
  [BEAUTY_SERVICE_TYPES.SHAPE_SMART_UPPER_THIGHS]: 'Shape Smart Локальное Похудение Верхняя Часть Бёдер (8 Сеансов)',
  [BEAUTY_SERVICE_TYPES.SHAPE_SMART_ABDOMEN]: 'Shape Smart Локальное Похудение Живот (8 Сеансов)',
  [BEAUTY_SERVICE_TYPES.SHAPE_SMART_FACE_LIFT]: 'Shape Smart Локальное Похудение Лифтинг Лица (8 Сеансов)',
  [BEAUTY_SERVICE_TYPES.SHAPE_SMART_LOWER_THIGHS]: 'Shape Smart Локальное Похудение Нижняя Часть Бёдер (8 Сеансов)',
  [BEAUTY_SERVICE_TYPES.SHAPE_SMART_CHIN]: 'Shape Smart Локальное Похудение Подбородок (8 Сеансов)',
  [BEAUTY_SERVICE_TYPES.SHAPE_SMART_LOWER_BACK]: 'Shape Smart Локальное Похудение Поясница (8 Сеансов)',
  [BEAUTY_SERVICE_TYPES.SHAPE_SMART_ARMS]: 'Shape Smart Локальное Похудение Руки (8 Сеансов)',
  [BEAUTY_SERVICE_TYPES.SHAPE_SMART_BACK]: 'Shape Smart Локальное Похудение Спина (8 Сеансов)',
  
  // Эпиляция
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_SIDEBURNS]: 'Лазерная Эпиляция Бакенбарды (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_THIGHS]: 'Лазерная Эпиляция Бёдра (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_UPPER_LIP]: 'Лазерная Эпиляция Верхняя Губа (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_UPPER_ARMS]: 'Лазерная Эпиляция Верхняя Часть Рук (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_UPPER_BUTTOCKS]: 'Лазерная Эпиляция Верхняя Часть Ягодиц (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_FULL_FACE]: 'Лазерная Эпиляция Всё Лицо (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_FULL_LEGS]: 'Лазерная Эпиляция Всё Ноги (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_FULL_ARMS]: 'Лазерная Эпиляция Всё Руки (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_FULL_BODY]: 'Лазерная Эпиляция Всё Тело (Подмышки, Генитальная Область, Всё Ноги) (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_GENITAL]: 'Лазерная Эпиляция Генитальная Область (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_SHINS]: 'Лазерная Эпиляция Голени (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_CHEST]: 'Лазерная Эпиляция Грудь (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_ABDOMEN]: 'Лазерная Эпиляция Живот (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_NAPE]: 'Лазерная Эпиляция Затылок (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_HANDS]: 'Лазерная Эпиляция Кисти (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_FOREHEAD]: 'Лазерная Эпиляция Лоб (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_LOWER_ARMS]: 'Лазерная Эпиляция Нижняя Часть Рук (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_CHIN]: 'Лазерная Эпиляция Подбородок (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_ARMPITS]: 'Лазерная Эпиляция Подмышки (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_LOWER_BACK]: 'Лазерная Эпиляция Поясница (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_BACK]: 'Лазерная Эпиляция Спина (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_FEET]: 'Лазерная Эпиляция Ступни (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_NECK]: 'Лазерная Эпиляция Шея (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_BUTTOCKS]: 'Лазерная Эпиляция Ягодицы (1 Сеанс)',
  
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_FULL_FACE]: 'Восковая депиляция – Всё лицо',
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_GENITAL]: 'Восковая депиляция – Генитальная зона',
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_PACKAGE]: 'Восковая депиляция – Пакет (Половина руки – Подмышки – Половина ноги – Генитальная зона)',
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_ARMPITS]: 'Восковая депиляция – Подмышечные впадины',
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_FULL_ARM]: 'Восковая депиляция – Полная рука',
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_FULL_LEGS]: 'Восковая депиляция – Полные ноги',
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_HALF_LEG]: 'Восковая депиляция – Половина ноги',
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_HALF_ARM]: 'Восковая депиляция – Половина руки',
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_LOWER_BACK]: 'Восковая депиляция – Поясница',
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_BACK]: 'Восковая депиляция – Спина',
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_MUSTACHE]: 'Восковая депиляция – Усики',
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_BUTTOCKS]: 'Восковая депиляция – Ягодицы',
  
  [BEAUTY_SERVICE_TYPES.NEEDLE_DEPILATION]: 'Игольчатая Эпиляция (Поминутно)',
  
  // Массаж
  [BEAUTY_SERVICE_TYPES.G8_MASSAGE]: 'G8 Массаж (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.G8_MASSAGE_THIGHS]: 'G8 Массаж Бёдра (8 Сеансов)',
  [BEAUTY_SERVICE_TYPES.G8_MASSAGE_UPPER_THIGHS]: 'G8 Массаж Верхняя Часть Бёдер (8 Сеансов)',
  [BEAUTY_SERVICE_TYPES.G8_MASSAGE_ABDOMEN]: 'G8 Массаж Живот (8 Сеансов)',
  [BEAUTY_SERVICE_TYPES.G8_MASSAGE_LOWER_THIGHS]: 'G8 Массаж Нижняя Часть Бёдер (8 Сеансов)',
  [BEAUTY_SERVICE_TYPES.G8_MASSAGE_LOWER_BACK]: 'G8 Массаж Поясница (8 Сеансов)',
  [BEAUTY_SERVICE_TYPES.G8_MASSAGE_BACK]: 'G8 Массаж Спина (8 Сеансов)',
  
  [BEAUTY_SERVICE_TYPES.ENDO_ROLLER_MASSAGE_UPPER_THIGHS]: 'Endo Roller Массаж Верхняя Часть Бёдер (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.ENDO_ROLLER_MASSAGE_LOWER_THIGHS]: 'Endo Roller Массаж Нижняя Часть Бёдер (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.ENDO_ROLLER_MASSAGE_LOWER_BACK]: 'Endo Roller Массаж Поясница (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.ENDO_ROLLER_MASSAGE_BACK]: 'Endo Roller Массаж Спина (1 Сеанс)',
  
  [BEAUTY_SERVICE_TYPES.EMS_SLIM_THIGHS]: 'EMS Slim Бёдра (8 Сеансов)',
  [BEAUTY_SERVICE_TYPES.EMS_SLIM_UPPER_THIGHS]: 'EMS Slim Верхняя Часть Бёдер (8 Сеансов)',
  [BEAUTY_SERVICE_TYPES.EMS_SLIM_ABDOMEN]: 'EMS Slim Живот (8 Сеансов)',
  
  [BEAUTY_SERVICE_TYPES.CLASSICAL_BODY_MASSAGE]: 'Классический Массаж Тела',
  [BEAUTY_SERVICE_TYPES.LYMPHODRAINAGE]: 'Лимфодренаж (1 сеанс)',
  [BEAUTY_SERVICE_TYPES.LYMPHODRAINAGE_FREE]: 'Лимфодренаж (4 сеанса в подарок)',
  [BEAUTY_SERVICE_TYPES.LYMPHODRAINAGE_8]: 'Лимфодренаж (8 сеанс)',
  [BEAUTY_SERVICE_TYPES.LYMPHODRAINAGE_FULL_BODY]: 'Лимфодренаж Всего Тела',
  [BEAUTY_SERVICE_TYPES.HAIR_MASSAGE_CARE]: 'Массаж И Уход За Волосами',
  [BEAUTY_SERVICE_TYPES.PASSIVE_GYMNASTICS]: 'Пассивная Гимнастика',
  [BEAUTY_SERVICE_TYPES.PASSIVE_GYMNASTICS_1]: 'Пассивная гимнастика (1 сеанс)',
  [BEAUTY_SERVICE_TYPES.PASSIVE_GYMNASTICS_FREE]: 'Пассивная гимнастика (4 сеанса в подарок)',
  [BEAUTY_SERVICE_TYPES.PASSIVE_GYMNASTICS_8]: 'Пассивная гимнастика (8 сеанс)',
  
  // Уход за лицом
  [BEAUTY_SERVICE_TYPES.HYDRAMASTER_BREAST_LIFT]: 'Hydramaster Подтяжка Груди (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.HYDRAMASTER_BUTTOCKS_LIFT]: 'Hydramaster Подтяжка Ягодиц (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.HYDRAMASTER_FACIAL_CARE]: 'Hydramaster Уход За Кожей Лица (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.HIFU_FACE_LIFT]: 'HIFU Лифтинг Лица (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.HIFU_CHIN_LIFT]: 'HIFU Лифтинг Подбородка (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.HIFU_SKIN_REJUVENATION]: 'HIFU Омоложение Кожи (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.HIFU_BROW_LIFT]: 'HIFU Поднятие Бровей (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.HIFU_WRINKLE_REDUCTION]: 'HIFU Уменьшение Морщин (1 Сеанс)',
  [BEAUTY_SERVICE_TYPES.CLASSICAL_FACIAL_CARE]: 'Классический Уход За Кожей Лица',
  
  // Услуги для ногтей
  [BEAUTY_SERVICE_TYPES.NAIL_POLISH]: 'Лак Для Ногтей',
  [BEAUTY_SERVICE_TYPES.MANICURE]: 'Маникюр',
  [BEAUTY_SERVICE_TYPES.MANICURE_FEET]: 'Маникюр ногтей на ногах',
  [BEAUTY_SERVICE_TYPES.NAIL_EXTENSION]: 'Наращивание Ногтей',
  [BEAUTY_SERVICE_TYPES.PEDICURE]: 'Педикюр',
  [BEAUTY_SERVICE_TYPES.PLASTIC_NAILS]: 'Пластиковые Ногти',
  [BEAUTY_SERVICE_TYPES.HEEL_CARE]: 'Уход За Пятками',
  [BEAUTY_SERVICE_TYPES.HENNA_NAILS]: 'Хна Для Ногтей',
  [BEAUTY_SERVICE_TYPES.SHELLAC]: 'Шеллак',
  
  // Фитнес
  [BEAUTY_SERVICE_TYPES.ZUMBA_MONTHLY]: 'Зумба (Ежемесячный Абонемент На 12 Занятий)',
  [BEAUTY_SERVICE_TYPES.ZUMBA_CLASS]: 'Зумба (Занятие)',
  [BEAUTY_SERVICE_TYPES.YOGA_MONTHLY]: 'Йога (Ежемесячный Абонемент, 3 Раза В Неделю)',
  [BEAUTY_SERVICE_TYPES.PILATES_GROUP]: 'Пилатес (Групповое Занятие)',
  [BEAUTY_SERVICE_TYPES.PILATES_INDIVIDUAL]: 'Пилатес (Индивидуальное Занятие)',
  [BEAUTY_SERVICE_TYPES.SPORTS_NUTRITION_PLANNING]: 'Планирование И Контроль Спортивного Питания',
  [BEAUTY_SERVICE_TYPES.FITNESS_12_MONTHS]: 'Фитнес (Абонемент На 12 Месяцев)',
  [BEAUTY_SERVICE_TYPES.FITNESS_3_MONTHS]: 'Фитнес (Абонемент На 3 Месяца)',
  [BEAUTY_SERVICE_TYPES.FITNESS_6_MONTHS]: 'Фитнес (Абонемент На 6 Месяцев)',
  
  // Старые услуги (для совместимости)
  [BEAUTY_SERVICE_TYPES.HAIRCUT]: 'Стрижка',
  [BEAUTY_SERVICE_TYPES.HAIR_COLORING]: 'Окрашивание волос',
  [BEAUTY_SERVICE_TYPES.HAIR_STYLING]: 'Укладка волос',
  [BEAUTY_SERVICE_TYPES.HAIR_TREATMENT]: 'Лечение волос',
  [BEAUTY_SERVICE_TYPES.HAIR_EXTENSION]: 'Наращивание волос',
  [BEAUTY_SERVICE_TYPES.FACIAL]: 'Уход за лицом',
  [BEAUTY_SERVICE_TYPES.CLEANING]: 'Чистка лица',
  [BEAUTY_SERVICE_TYPES.PEELING]: 'Пилинг',
  [BEAUTY_SERVICE_TYPES.MASK]: 'Маска',
  [BEAUTY_SERVICE_TYPES.MICRODERMABRASION]: 'Микродермабразия',
  [BEAUTY_SERVICE_TYPES.EYEBROW]: 'Брови',
  [BEAUTY_SERVICE_TYPES.EYELASH]: 'Ресницы',
  [BEAUTY_SERVICE_TYPES.EYELASH_EXTENSION]: 'Наращивание ресниц',
  [BEAUTY_SERVICE_TYPES.BODY_MASSAGE]: 'Массаж тела',
  [BEAUTY_SERVICE_TYPES.BODY_WRAP]: 'Обертывание тела',
  [BEAUTY_SERVICE_TYPES.BODY_SCRUB]: 'Скраб для тела',
  [BEAUTY_SERVICE_TYPES.DEPILATION]: 'Депиляция',
  [BEAUTY_SERVICE_TYPES.NAIL_ART]: 'Дизайн ногтей',
  [BEAUTY_SERVICE_TYPES.GEL_NAILS]: 'Гель-лак',
  [BEAUTY_SERVICE_TYPES.MAKEUP]: 'Макияж',
  [BEAUTY_SERVICE_TYPES.BRIDAL_MAKEUP]: 'Свадебный макияж',
  [BEAUTY_SERVICE_TYPES.EVENT_MAKEUP]: 'Макияж для мероприятия',
  [BEAUTY_SERVICE_TYPES.CONSULTATION]: 'Консультация',
  [BEAUTY_SERVICE_TYPES.OTHER]: 'Другое'
}

// Xizmatlar narxlari (Rus tilida)
export const BEAUTY_SERVICE_PRICES = {
  // Золотая Игла
  [BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_ACNE_TREATMENT]: 4800000,
  [BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_WRINKLE_TREATMENT]: 4800000,
  [BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_BURN_SCAR_TREATMENT]: 4800000,
  [BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_PIGMENT_SPOT_TREATMENT]: 4800000,
  [BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_STRETCH_MARK_TREATMENT]: 3000000,
  [BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_ACNE_SCAR_TREATMENT]: 4800000,
  [BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_SKIN_REJUVENATION]: null, // Narx yo'q
  [BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_PORE_TIGHTENING]: 4800000,
  
  // BBL Лазер
  [BEAUTY_SERVICE_TYPES.BBL_LASER_FRECKLE_TREATMENT]: 3600000,
  [BEAUTY_SERVICE_TYPES.BBL_LASER_MELASMA_TREATMENT]: 3600000,
  [BEAUTY_SERVICE_TYPES.BBL_LASER_PIGMENT_SPOT_TREATMENT]: 3600000,
  [BEAUTY_SERVICE_TYPES.BBL_LASER_REDNESS_TREATMENT]: 3600000,
  [BEAUTY_SERVICE_TYPES.BBL_LASER_ENLARGED_PORE_TREATMENT]: 3600000,
  [BEAUTY_SERVICE_TYPES.BBL_LASER_BIRTHMARK_TREATMENT]: 3600000,
  [BEAUTY_SERVICE_TYPES.BBL_LASER_ROSACEA_TREATMENT]: 3600000,
  
  // ND YAG Лазер
  [BEAUTY_SERVICE_TYPES.ND_YAG_CARBON_PEELING]: 2600000,
  [BEAUTY_SERVICE_TYPES.ND_YAG_BROW_TATTOO_REMOVAL]: 2600000,
  [BEAUTY_SERVICE_TYPES.ND_YAG_TATTOO_REMOVAL]: 6000000,
  
  // Фракционный Лазер
  [BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_VAGINAL_TIGHTENING]: 6000000,
  [BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_WRINKLE_TREATMENT]: 3000000,
  [BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_BURN_SCAR_TREATMENT]: 3000000,
  [BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_PIGMENT_SPOT_TREATMENT]: 3000000,
  [BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_POST_SURGICAL_SCAR_TREATMENT]: 3000000,
  [BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_STRETCH_MARK_TREATMENT]: 3000000,
  [BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_SCAR_TREATMENT]: 3000000,
  [BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_SUN_SPOT_TREATMENT]: 3000000,
  
  // Coolite Pro Лазер
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_UPPER_LIP]: 190000,
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_UPPER_THIGH]: 720000,
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_UPPER_ARM]: 360000,
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_FULL_FACE]: 720000,
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_FULL_LEGS]: 1900000,
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_FULL_BODY]: 4800000,
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_FULL_ARM]: 720000,
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_CHEST]: 550000,
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_NAPE]: 400000,
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_FOREHEAD]: 240000,
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_LOWER_THIGH]: 720000,
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_LOWER_ARM]: 440000,
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_LOWER_BUTTOCKS]: 720000,
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_PERINEAL]: 440000,
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_CHIN]: 190000,
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_ARMPITS]: 720000,
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_BUTTOCKS]: 440000,
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_LOWER_BACK]: 440000,
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_ARM]: 440000,
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_BACK]: 720000,
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_FEET]: 440000,
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_MUSTACHE]: 240000,
  [BEAUTY_SERVICE_TYPES.COOLITE_PRO_NECK]: 192000,
  
  // Похудение
  [BEAUTY_SERVICE_TYPES.SHAPE_SMART_LOCAL_WEIGHT_LOSS]: 4000000,
  [BEAUTY_SERVICE_TYPES.SHAPE_SMART_THIGHS]: 4000000,
  [BEAUTY_SERVICE_TYPES.SHAPE_SMART_UPPER_THIGHS]: 4000000,
  [BEAUTY_SERVICE_TYPES.SHAPE_SMART_ABDOMEN]: 4000000,
  [BEAUTY_SERVICE_TYPES.SHAPE_SMART_FACE_LIFT]: 4000000,
  [BEAUTY_SERVICE_TYPES.SHAPE_SMART_LOWER_THIGHS]: 4000000,
  [BEAUTY_SERVICE_TYPES.SHAPE_SMART_CHIN]: 4000000,
  [BEAUTY_SERVICE_TYPES.SHAPE_SMART_LOWER_BACK]: 4000000,
  [BEAUTY_SERVICE_TYPES.SHAPE_SMART_ARMS]: 4000000,
  [BEAUTY_SERVICE_TYPES.SHAPE_SMART_BACK]: 4000000,
  
  // Эпиляция
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_SIDEBURNS]: 240000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_THIGHS]: 720000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_UPPER_LIP]: 192000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_UPPER_ARMS]: 360000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_UPPER_BUTTOCKS]: 720000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_FULL_FACE]: 720000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_FULL_LEGS]: 1920000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_FULL_ARMS]: 720000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_FULL_BODY]: 4800000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_GENITAL]: 432000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_SHINS]: 720000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_CHEST]: 552000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_ABDOMEN]: 552000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_NAPE]: 408000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_HANDS]: 432000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_FOREHEAD]: 240000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_LOWER_ARMS]: 432000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_CHIN]: 192000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_ARMPITS]: 720000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_LOWER_BACK]: 432000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_BACK]: 720000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_FEET]: 432000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_NECK]: 192000,
  [BEAUTY_SERVICE_TYPES.LASER_DEPILATION_BUTTOCKS]: 432000,
  
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_FULL_FACE]: 60000,
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_GENITAL]: 90000,
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_PACKAGE]: 200000,
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_ARMPITS]: 40000,
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_FULL_ARM]: 60000,
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_FULL_LEGS]: 120000,
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_HALF_LEG]: 60000,
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_HALF_ARM]: 40000,
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_LOWER_BACK]: 75000,
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_BACK]: 75000,
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_MUSTACHE]: 20000,
  [BEAUTY_SERVICE_TYPES.WAX_DEPILATION_BUTTOCKS]: 60000,
  
  [BEAUTY_SERVICE_TYPES.NEEDLE_DEPILATION]: 76000, // Поминутно
  
  // Массаж
  [BEAUTY_SERVICE_TYPES.G8_MASSAGE]: 450000,
  [BEAUTY_SERVICE_TYPES.G8_MASSAGE_THIGHS]: 3600000,
  [BEAUTY_SERVICE_TYPES.G8_MASSAGE_UPPER_THIGHS]: 3600000,
  [BEAUTY_SERVICE_TYPES.G8_MASSAGE_ABDOMEN]: 3600000,
  [BEAUTY_SERVICE_TYPES.G8_MASSAGE_LOWER_THIGHS]: 3600000,
  [BEAUTY_SERVICE_TYPES.G8_MASSAGE_LOWER_BACK]: 3600000,
  [BEAUTY_SERVICE_TYPES.G8_MASSAGE_BACK]: 3600000,
  
  [BEAUTY_SERVICE_TYPES.ENDO_ROLLER_MASSAGE_UPPER_THIGHS]: 500000,
  [BEAUTY_SERVICE_TYPES.ENDO_ROLLER_MASSAGE_LOWER_THIGHS]: 500000,
  [BEAUTY_SERVICE_TYPES.ENDO_ROLLER_MASSAGE_LOWER_BACK]: 500000,
  [BEAUTY_SERVICE_TYPES.ENDO_ROLLER_MASSAGE_BACK]: 500000,
  
  [BEAUTY_SERVICE_TYPES.EMS_SLIM_THIGHS]: 3600000,
  [BEAUTY_SERVICE_TYPES.EMS_SLIM_UPPER_THIGHS]: 3600000,
  [BEAUTY_SERVICE_TYPES.EMS_SLIM_ABDOMEN]: 3600000,
  
  [BEAUTY_SERVICE_TYPES.CLASSICAL_BODY_MASSAGE]: 400000,
  [BEAUTY_SERVICE_TYPES.LYMPHODRAINAGE]: 500000,
  [BEAUTY_SERVICE_TYPES.LYMPHODRAINAGE_FREE]: 0,
  [BEAUTY_SERVICE_TYPES.LYMPHODRAINAGE_8]: 4000000,
  [BEAUTY_SERVICE_TYPES.LYMPHODRAINAGE_FULL_BODY]: 500000,
  [BEAUTY_SERVICE_TYPES.HAIR_MASSAGE_CARE]: 400000,
  [BEAUTY_SERVICE_TYPES.PASSIVE_GYMNASTICS]: 400000,
  [BEAUTY_SERVICE_TYPES.PASSIVE_GYMNASTICS_1]: 400000,
  [BEAUTY_SERVICE_TYPES.PASSIVE_GYMNASTICS_FREE]: 0,
  [BEAUTY_SERVICE_TYPES.PASSIVE_GYMNASTICS_8]: 3200000,
  
  // Уход за лицом
  [BEAUTY_SERVICE_TYPES.HYDRAMASTER_BREAST_LIFT]: 700000,
  [BEAUTY_SERVICE_TYPES.HYDRAMASTER_BUTTOCKS_LIFT]: 1000000,
  [BEAUTY_SERVICE_TYPES.HYDRAMASTER_FACIAL_CARE]: 700000,
  [BEAUTY_SERVICE_TYPES.HIFU_FACE_LIFT]: 3000000,
  [BEAUTY_SERVICE_TYPES.HIFU_CHIN_LIFT]: 3000000,
  [BEAUTY_SERVICE_TYPES.HIFU_SKIN_REJUVENATION]: 3000000,
  [BEAUTY_SERVICE_TYPES.HIFU_BROW_LIFT]: 3000000,
  [BEAUTY_SERVICE_TYPES.HIFU_WRINKLE_REDUCTION]: 3000000,
  [BEAUTY_SERVICE_TYPES.CLASSICAL_FACIAL_CARE]: 500000,
  
  // Услуги для ногтей
  [BEAUTY_SERVICE_TYPES.NAIL_POLISH]: 100000,
  [BEAUTY_SERVICE_TYPES.MANICURE]: 80000,
  [BEAUTY_SERVICE_TYPES.MANICURE_FEET]: 80000,
  [BEAUTY_SERVICE_TYPES.NAIL_EXTENSION]: 400000,
  [BEAUTY_SERVICE_TYPES.PEDICURE]: 150000,
  [BEAUTY_SERVICE_TYPES.PLASTIC_NAILS]: 230000,
  [BEAUTY_SERVICE_TYPES.HEEL_CARE]: 250000,
  [BEAUTY_SERVICE_TYPES.HENNA_NAILS]: 100000,
  [BEAUTY_SERVICE_TYPES.SHELLAC]: 180000,
  
  // Фитнес
  [BEAUTY_SERVICE_TYPES.ZUMBA_MONTHLY]: 400000,
  [BEAUTY_SERVICE_TYPES.ZUMBA_CLASS]: 80000,
  [BEAUTY_SERVICE_TYPES.YOGA_MONTHLY]: 600000,
  [BEAUTY_SERVICE_TYPES.PILATES_GROUP]: 120000,
  [BEAUTY_SERVICE_TYPES.PILATES_INDIVIDUAL]: 200000,
  [BEAUTY_SERVICE_TYPES.SPORTS_NUTRITION_PLANNING]: 600000,
  [BEAUTY_SERVICE_TYPES.FITNESS_12_MONTHS]: 4200000,
  [BEAUTY_SERVICE_TYPES.FITNESS_3_MONTHS]: 1200000,
  [BEAUTY_SERVICE_TYPES.FITNESS_6_MONTHS]: 2250000
}

// Xizmat turlarini kategoriyalarga bo'lish - Rus tilida
export const BEAUTY_SERVICE_CATEGORIES = {
  LASER_PROCEDURES: {
    label: 'Лазерные процедуры',
    services: [
      // Золотая Игла
      BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_ACNE_TREATMENT,
      BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_WRINKLE_TREATMENT,
      BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_BURN_SCAR_TREATMENT,
      BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_PIGMENT_SPOT_TREATMENT,
      BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_STRETCH_MARK_TREATMENT,
      BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_ACNE_SCAR_TREATMENT,
      BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_SKIN_REJUVENATION,
      BEAUTY_SERVICE_TYPES.GOLDEN_NEEDLE_PORE_TIGHTENING,
      // BBL Лазер
      BEAUTY_SERVICE_TYPES.BBL_LASER_FRECKLE_TREATMENT,
      BEAUTY_SERVICE_TYPES.BBL_LASER_MELASMA_TREATMENT,
      BEAUTY_SERVICE_TYPES.BBL_LASER_PIGMENT_SPOT_TREATMENT,
      BEAUTY_SERVICE_TYPES.BBL_LASER_REDNESS_TREATMENT,
      BEAUTY_SERVICE_TYPES.BBL_LASER_ENLARGED_PORE_TREATMENT,
      BEAUTY_SERVICE_TYPES.BBL_LASER_BIRTHMARK_TREATMENT,
      BEAUTY_SERVICE_TYPES.BBL_LASER_ROSACEA_TREATMENT,
      // ND YAG Лазер
      BEAUTY_SERVICE_TYPES.ND_YAG_CARBON_PEELING,
      BEAUTY_SERVICE_TYPES.ND_YAG_BROW_TATTOO_REMOVAL,
      BEAUTY_SERVICE_TYPES.ND_YAG_TATTOO_REMOVAL,
      // Фракционный Лазер
      BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_VAGINAL_TIGHTENING,
      BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_WRINKLE_TREATMENT,
      BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_BURN_SCAR_TREATMENT,
      BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_PIGMENT_SPOT_TREATMENT,
      BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_POST_SURGICAL_SCAR_TREATMENT,
      BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_STRETCH_MARK_TREATMENT,
      BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_SCAR_TREATMENT,
      BEAUTY_SERVICE_TYPES.FRACTIONAL_LASER_SUN_SPOT_TREATMENT,
      // Coolite Pro Лазер
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_UPPER_LIP,
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_UPPER_THIGH,
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_UPPER_ARM,
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_FULL_FACE,
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_FULL_LEGS,
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_FULL_BODY,
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_FULL_ARM,
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_CHEST,
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_NAPE,
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_FOREHEAD,
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_LOWER_THIGH,
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_LOWER_ARM,
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_LOWER_BUTTOCKS,
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_PERINEAL,
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_CHIN,
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_ARMPITS,
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_BUTTOCKS,
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_LOWER_BACK,
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_ARM,
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_BACK,
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_FEET,
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_MUSTACHE,
      BEAUTY_SERVICE_TYPES.COOLITE_PRO_NECK
    ]
  },
  BODY_SHAPING: {
    label: 'Похудение и коррекция фигуры',
    services: [
      BEAUTY_SERVICE_TYPES.SHAPE_SMART_LOCAL_WEIGHT_LOSS,
      BEAUTY_SERVICE_TYPES.SHAPE_SMART_THIGHS,
      BEAUTY_SERVICE_TYPES.SHAPE_SMART_UPPER_THIGHS,
      BEAUTY_SERVICE_TYPES.SHAPE_SMART_ABDOMEN,
      BEAUTY_SERVICE_TYPES.SHAPE_SMART_FACE_LIFT,
      BEAUTY_SERVICE_TYPES.SHAPE_SMART_LOWER_THIGHS,
      BEAUTY_SERVICE_TYPES.SHAPE_SMART_CHIN,
      BEAUTY_SERVICE_TYPES.SHAPE_SMART_LOWER_BACK,
      BEAUTY_SERVICE_TYPES.SHAPE_SMART_ARMS,
      BEAUTY_SERVICE_TYPES.SHAPE_SMART_BACK
    ]
  },
  DEPILATION: {
    label: 'Эпиляция',
    services: [
      // Лазерная Эпиляция
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_SIDEBURNS,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_THIGHS,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_UPPER_LIP,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_UPPER_ARMS,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_UPPER_BUTTOCKS,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_FULL_FACE,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_FULL_LEGS,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_FULL_ARMS,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_FULL_BODY,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_GENITAL,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_SHINS,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_CHEST,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_ABDOMEN,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_NAPE,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_HANDS,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_FOREHEAD,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_LOWER_ARMS,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_CHIN,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_ARMPITS,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_LOWER_BACK,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_BACK,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_FEET,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_NECK,
      BEAUTY_SERVICE_TYPES.LASER_DEPILATION_BUTTOCKS,
      // Восковая депиляция
      BEAUTY_SERVICE_TYPES.WAX_DEPILATION_FULL_FACE,
      BEAUTY_SERVICE_TYPES.WAX_DEPILATION_GENITAL,
      BEAUTY_SERVICE_TYPES.WAX_DEPILATION_PACKAGE,
      BEAUTY_SERVICE_TYPES.WAX_DEPILATION_ARMPITS,
      BEAUTY_SERVICE_TYPES.WAX_DEPILATION_FULL_ARM,
      BEAUTY_SERVICE_TYPES.WAX_DEPILATION_FULL_LEGS,
      BEAUTY_SERVICE_TYPES.WAX_DEPILATION_HALF_LEG,
      BEAUTY_SERVICE_TYPES.WAX_DEPILATION_HALF_ARM,
      BEAUTY_SERVICE_TYPES.WAX_DEPILATION_LOWER_BACK,
      BEAUTY_SERVICE_TYPES.WAX_DEPILATION_BACK,
      BEAUTY_SERVICE_TYPES.WAX_DEPILATION_MUSTACHE,
      BEAUTY_SERVICE_TYPES.WAX_DEPILATION_BUTTOCKS,
      // Игольчатая Эпиляция
      BEAUTY_SERVICE_TYPES.NEEDLE_DEPILATION
    ]
  },
  MASSAGE: {
    label: 'Массаж',
    services: [
      BEAUTY_SERVICE_TYPES.G8_MASSAGE,
      BEAUTY_SERVICE_TYPES.G8_MASSAGE_THIGHS,
      BEAUTY_SERVICE_TYPES.G8_MASSAGE_UPPER_THIGHS,
      BEAUTY_SERVICE_TYPES.G8_MASSAGE_ABDOMEN,
      BEAUTY_SERVICE_TYPES.G8_MASSAGE_LOWER_THIGHS,
      BEAUTY_SERVICE_TYPES.G8_MASSAGE_LOWER_BACK,
      BEAUTY_SERVICE_TYPES.G8_MASSAGE_BACK,
      BEAUTY_SERVICE_TYPES.ENDO_ROLLER_MASSAGE_UPPER_THIGHS,
      BEAUTY_SERVICE_TYPES.ENDO_ROLLER_MASSAGE_LOWER_THIGHS,
      BEAUTY_SERVICE_TYPES.ENDO_ROLLER_MASSAGE_LOWER_BACK,
      BEAUTY_SERVICE_TYPES.ENDO_ROLLER_MASSAGE_BACK,
      BEAUTY_SERVICE_TYPES.EMS_SLIM_THIGHS,
      BEAUTY_SERVICE_TYPES.EMS_SLIM_UPPER_THIGHS,
      BEAUTY_SERVICE_TYPES.EMS_SLIM_ABDOMEN,
      BEAUTY_SERVICE_TYPES.CLASSICAL_BODY_MASSAGE,
      BEAUTY_SERVICE_TYPES.LYMPHODRAINAGE,
      BEAUTY_SERVICE_TYPES.LYMPHODRAINAGE_FREE,
      BEAUTY_SERVICE_TYPES.LYMPHODRAINAGE_8,
      BEAUTY_SERVICE_TYPES.LYMPHODRAINAGE_FULL_BODY,
      BEAUTY_SERVICE_TYPES.HAIR_MASSAGE_CARE,
      BEAUTY_SERVICE_TYPES.PASSIVE_GYMNASTICS,
      BEAUTY_SERVICE_TYPES.PASSIVE_GYMNASTICS_1,
      BEAUTY_SERVICE_TYPES.PASSIVE_GYMNASTICS_FREE,
      BEAUTY_SERVICE_TYPES.PASSIVE_GYMNASTICS_8
    ]
  },
  FACIAL_CARE: {
    label: 'Уход за лицом',
    services: [
      BEAUTY_SERVICE_TYPES.HYDRAMASTER_BREAST_LIFT,
      BEAUTY_SERVICE_TYPES.HYDRAMASTER_BUTTOCKS_LIFT,
      BEAUTY_SERVICE_TYPES.HYDRAMASTER_FACIAL_CARE,
      BEAUTY_SERVICE_TYPES.HIFU_FACE_LIFT,
      BEAUTY_SERVICE_TYPES.HIFU_CHIN_LIFT,
      BEAUTY_SERVICE_TYPES.HIFU_SKIN_REJUVENATION,
      BEAUTY_SERVICE_TYPES.HIFU_BROW_LIFT,
      BEAUTY_SERVICE_TYPES.HIFU_WRINKLE_REDUCTION,
      BEAUTY_SERVICE_TYPES.CLASSICAL_FACIAL_CARE
    ]
  },
  NAIL_SERVICES: {
    label: 'Услуги для ногтей',
    services: [
      BEAUTY_SERVICE_TYPES.NAIL_POLISH,
      BEAUTY_SERVICE_TYPES.MANICURE,
      BEAUTY_SERVICE_TYPES.MANICURE_FEET,
      BEAUTY_SERVICE_TYPES.NAIL_EXTENSION,
      BEAUTY_SERVICE_TYPES.PEDICURE,
      BEAUTY_SERVICE_TYPES.PLASTIC_NAILS,
      BEAUTY_SERVICE_TYPES.HEEL_CARE,
      BEAUTY_SERVICE_TYPES.HENNA_NAILS,
      BEAUTY_SERVICE_TYPES.SHELLAC
    ]
  },
  FITNESS: {
    label: 'Фитнес',
    services: [
      BEAUTY_SERVICE_TYPES.ZUMBA_MONTHLY,
      BEAUTY_SERVICE_TYPES.ZUMBA_CLASS,
      BEAUTY_SERVICE_TYPES.YOGA_MONTHLY,
      BEAUTY_SERVICE_TYPES.PILATES_GROUP,
      BEAUTY_SERVICE_TYPES.PILATES_INDIVIDUAL,
      BEAUTY_SERVICE_TYPES.SPORTS_NUTRITION_PLANNING,
      BEAUTY_SERVICE_TYPES.FITNESS_12_MONTHS,
      BEAUTY_SERVICE_TYPES.FITNESS_3_MONTHS,
      BEAUTY_SERVICE_TYPES.FITNESS_6_MONTHS
    ]
  },
  // Старые категории (для совместимости)
  HAIR: {
    label: 'Услуги для волос',
    services: [
      BEAUTY_SERVICE_TYPES.HAIRCUT,
      BEAUTY_SERVICE_TYPES.HAIR_COLORING,
      BEAUTY_SERVICE_TYPES.HAIR_STYLING,
      BEAUTY_SERVICE_TYPES.HAIR_TREATMENT,
      BEAUTY_SERVICE_TYPES.HAIR_EXTENSION
    ]
  },
  FACE: {
    label: 'Услуги для лица',
    services: [
      BEAUTY_SERVICE_TYPES.FACIAL,
      BEAUTY_SERVICE_TYPES.CLEANING,
      BEAUTY_SERVICE_TYPES.PEELING,
      BEAUTY_SERVICE_TYPES.MASK,
      BEAUTY_SERVICE_TYPES.MICRODERMABRASION
    ]
  },
  EYES: {
    label: 'Услуги для глаз',
    services: [
      BEAUTY_SERVICE_TYPES.EYEBROW,
      BEAUTY_SERVICE_TYPES.EYELASH,
      BEAUTY_SERVICE_TYPES.EYELASH_EXTENSION
    ]
  },
  BODY: {
    label: 'Услуги для тела',
    services: [
      BEAUTY_SERVICE_TYPES.BODY_MASSAGE,
      BEAUTY_SERVICE_TYPES.BODY_WRAP,
      BEAUTY_SERVICE_TYPES.BODY_SCRUB,
      BEAUTY_SERVICE_TYPES.DEPILATION
    ]
  },
  HANDS_FEET: {
    label: 'Услуги для рук и ног',
    services: [
      BEAUTY_SERVICE_TYPES.MANICURE,
      BEAUTY_SERVICE_TYPES.PEDICURE,
      BEAUTY_SERVICE_TYPES.NAIL_ART,
      BEAUTY_SERVICE_TYPES.GEL_NAILS
    ]
  },
  MAKEUP: {
    label: 'Услуги макияжа',
    services: [
      BEAUTY_SERVICE_TYPES.MAKEUP,
      BEAUTY_SERVICE_TYPES.BRIDAL_MAKEUP,
      BEAUTY_SERVICE_TYPES.EVENT_MAKEUP
    ]
  },
  OTHER: {
    label: 'Другое',
    services: [
      BEAUTY_SERVICE_TYPES.CONSULTATION,
      BEAUTY_SERVICE_TYPES.OTHER
    ]
  }
}

// Xizmat turini tekshirish funksiyasi
export function isValidServiceType(serviceType) {
  return Object.values(BEAUTY_SERVICE_TYPES).includes(serviceType)
}

// Barcha xizmat turlarini array sifatida qaytarish
export function getAllServiceTypes() {
  return Object.values(BEAUTY_SERVICE_TYPES)
}

// Xizmat turini label bilan qaytarish
export function getServiceLabel(serviceType) {
  return BEAUTY_SERVICE_LABELS[serviceType] || serviceType
}

// Xizmat narxini olish
export function getServicePrice(serviceType) {
  return BEAUTY_SERVICE_PRICES[serviceType] || null
}
